// Paint layers for the Length and Alpha masks.
//
// A mask layer holds two channels of the same size as the old flat buffer:
//   value : the mask value, exactly what the flat buffer used to hold
//   cover : how much of this layer is actually painted (0 = untouched, 255 = solid)
//
// The cover channel is what makes layering possible at all - without it a mask layer
// cannot tell "painted black" from "not painted". The stack composites bottom to top
// starting from 0, which is what the single zeroed buffer used to give.
//
// The Direction field deliberately stays flat; blending two vector fields raises
// questions this tool does not need to answer.

using System;
using System.Collections.Generic;
using System.IO;
using UnityEngine;

namespace FurGroomingTool
{
    public enum MaskBlend { Normal, Min, Max }

    [Serializable]
    public class MaskLayer
    {
        public string name = "Layer";
        public float[] value;
        public byte[] cover;
        public bool visible = true;
        public float opacity = 1f;
        public MaskBlend blend = MaskBlend.Normal;
        public bool locked;      // no brush, no whole-canvas op
        public bool isResolver;  // regenerated by the occlusion resolver, not by hand

        // Set by the last composite: covered everywhere, fully opaque and blending Normal,
        // so nothing below this layer can show. The panel warns about it - two solid layers
        // with an erased hole each cancel out, which is a miserable thing to find by eye.
        [NonSerialized] public bool solid;

        public MaskLayer() { }

        public MaskLayer(string n, int size)
        {
            name = n;
            value = new float[size];
            cover = new byte[size];
        }

        public int Size { get { return value != null ? value.Length : 0; } }

        public void EnsureSize(int size)
        {
            if (value == null || value.Length != size) value = new float[size];
            if (cover == null || cover.Length != size) cover = new byte[size];
        }

        public void Clear()
        {
            if (value != null) Array.Clear(value, 0, value.Length);
            if (cover != null) Array.Clear(cover, 0, cover.Length);
        }

        public MaskLayer Clone()
        {
            return new MaskLayer
            {
                name = name,
                value = value != null ? (float[])value.Clone() : null,
                cover = cover != null ? (byte[])cover.Clone() : null,
                visible = visible,
                opacity = opacity,
                blend = blend,
                locked = locked,
                isResolver = isResolver
            };
        }

        // Paint coverage in by the same weight the value lerp uses, so the two rise
        // together. Rounded away from the current value so a very light flow still
        // makes progress instead of stalling on the byte grid.
        public static byte Raise(byte c, float w)
        {
            if (w <= 0f) return c;
            int v = Mathf.CeilToInt(Mathf.Lerp(c, 255f, Mathf.Clamp01(w)));
            return (byte)Mathf.Clamp(v, c, 255);
        }

        public static byte Lower(byte c, float w)
        {
            if (w <= 0f) return c;
            int v = Mathf.FloorToInt(Mathf.Lerp(c, 0f, Mathf.Clamp01(w)));
            return (byte)Mathf.Clamp(v, 0, c);
        }
    }

    [Serializable]
    public class MaskLayerStack
    {
        public List<MaskLayer> layers = new List<MaskLayer>();
        public int active;

        // Rebuilt lazily; rides on the window's existing maskDirty flag so a stroke
        // costs one recomposite per repaint rather than one per brush dab.
        [NonSerialized] float[] cache;
        [NonSerialized] bool cacheDirty = true;

        public int Count { get { return layers != null ? layers.Count : 0; } }

        public MaskLayer Active
        {
            get
            {
                if (layers == null || layers.Count == 0) return null;
                return layers[Mathf.Clamp(active, 0, layers.Count - 1)];
            }
        }

        public MaskLayer At(int i)
        {
            if (layers == null || i < 0 || i >= layers.Count) return null;
            return layers[i];
        }

        public void MarkDirty() { cacheDirty = true; }

        public void Ensure(int size, string baseName)
        {
            if (layers == null) layers = new List<MaskLayer>();
            for (int i = layers.Count - 1; i >= 0; i--) if (layers[i] == null) layers.RemoveAt(i);
            if (layers.Count == 0) layers.Add(new MaskLayer(baseName, size));
            for (int i = 0; i < layers.Count; i++) layers[i].EnsureSize(size);
            active = Mathf.Clamp(active, 0, layers.Count - 1);
            cacheDirty = true;
        }

        // ---- structure

        public MaskLayer Add(string name, int size)
        {
            var L = new MaskLayer(name, size);
            int at = Mathf.Clamp(active + 1, 0, layers.Count);
            layers.Insert(at, L);
            active = at;
            cacheDirty = true;
            return L;
        }

        public MaskLayer Duplicate(int i)
        {
            if (i < 0 || i >= layers.Count) return null;
            MaskLayer L = layers[i].Clone();
            L.name = layers[i].name + " copy";
            L.locked = false; L.isResolver = false;   // a copy is a normal hand-painted layer
            layers.Insert(i + 1, L);
            active = i + 1;
            cacheDirty = true;
            return L;
        }

        // The bottom layer is the foundation the whole mask composites onto, so it is not
        // deletable - losing it silently drops everything the layers above are painted over.
        // Reorder first if you want it gone: whichever layer ends up at the bottom is the
        // protected one. A generated resolver layer is exempt; it is never hand-painted.
        public bool CanDelete(int i)
        {
            if (layers == null || layers.Count <= 1 || i < 0 || i >= layers.Count) return false;
            return i != 0 || layers[i].isResolver;
        }

        public bool Delete(int i)
        {
            if (!CanDelete(i)) return false;
            layers.RemoveAt(i);
            active = Mathf.Clamp(active > i ? active - 1 : active, 0, layers.Count - 1);
            cacheDirty = true;
            return true;
        }

        public bool Move(int i, int delta)
        {
            int j = i + delta;
            if (i < 0 || i >= layers.Count || j < 0 || j >= layers.Count) return false;
            MaskLayer L = layers[i];
            layers.RemoveAt(i);
            layers.Insert(j, L);
            if (active == i) active = j;
            else if (active == j) active = i;
            cacheDirty = true;
            return true;
        }

        // ---- the resolver's own layer

        public int ResolverIndex()
        {
            for (int i = 0; i < layers.Count; i++) if (layers[i].isResolver) return i;
            return -1;
        }

        // Find the resolver layer, or put a fresh one on top of the stack.
        public MaskLayer EnsureResolver(int size, string name)
        {
            int i = ResolverIndex();
            if (i >= 0) { layers[i].EnsureSize(size); return layers[i]; }
            var L = new MaskLayer(name, size) { blend = MaskBlend.Min, locked = true, isResolver = true };
            layers.Add(L);
            cacheDirty = true;
            return L;
        }

        // ---- compositing

        public float[] Composite()
        {
            int size = Size();
            if (cache == null || cache.Length != size) { cache = new float[size]; cacheDirty = true; }
            if (cacheDirty) { CompositeInto(cache, layers.Count); cacheDirty = false; }
            return cache;
        }

        // Everything strictly below `index`, into a fresh array. Used to hand the
        // resolver the groom it must resolve against, without its own layer folded in.
        public float[] CompositeBelow(int index)
        {
            var dst = new float[Size()];
            CompositeInto(dst, Mathf.Clamp(index, 0, layers.Count));
            return dst;
        }

        public int Size()
        {
            for (int i = 0; i < layers.Count; i++) if (layers[i].Size > 0) return layers[i].Size;
            return 0;
        }

        [NonSerialized] float[] alphaLut;
        [NonSerialized] float alphaLutFor = -1f;

        float[] Alpha255(float opacity)
        {
            if (alphaLut != null && alphaLutFor == opacity) return alphaLut;
            if (alphaLut == null) alphaLut = new float[256];
            for (int k = 0; k < 256; k++) alphaLut[k] = (k / 255f) * opacity;
            alphaLutFor = opacity;
            return alphaLut;
        }

        public void CompositeInto(float[] dst, int count)
        {
            Array.Clear(dst, 0, dst.Length);
            count = Mathf.Clamp(count, 0, layers.Count);
            for (int li = 0; li < count; li++)
            {
                MaskLayer L = layers[li];
                if (L == null) continue;
                L.solid = false;
                if (!L.visible || L.opacity <= 0f) continue;
                float[] v = L.value; byte[] c = L.cover;
                if (v == null || c == null || v.Length != dst.Length) continue;

                int low = 255;   // the least-covered texel, for the solid-layer check below

                // Coverage times opacity, via a table: 255 at opacity 1 must land on exactly
                // 1.0 so a solid layer is an exact replace, not a replace minus one ulp.
                float[] a255 = Alpha255(Mathf.Clamp01(L.opacity));

                switch (L.blend)
                {
                    case MaskBlend.Min:
                        for (int i = 0; i < dst.Length; i++)
                        {
                            byte cv = c[i]; if (cv < low) low = cv;
                            float a = a255[cv]; if (a <= 0f) continue;
                            float o = dst[i];
                            dst[i] = o + (Mathf.Min(o, v[i]) - o) * a;
                        }
                        break;
                    case MaskBlend.Max:
                        for (int i = 0; i < dst.Length; i++)
                        {
                            byte cv = c[i]; if (cv < low) low = cv;
                            float a = a255[cv]; if (a <= 0f) continue;
                            float o = dst[i];
                            dst[i] = o + (Mathf.Max(o, v[i]) - o) * a;
                        }
                        break;
                    default:
                        for (int i = 0; i < dst.Length; i++)
                        {
                            byte cv = c[i]; if (cv < low) low = cv;
                            float a = a255[cv]; if (a <= 0f) continue;
                            dst[i] += (v[i] - dst[i]) * a;
                        }
                        break;
                }

                L.solid = low == 255 && L.blend == MaskBlend.Normal && L.opacity >= 1f;
            }
        }

        // ---- copying

        public MaskLayerStack CloneDeep()
        {
            var s = new MaskLayerStack { active = active, layers = new List<MaskLayer>(layers.Count) };
            for (int i = 0; i < layers.Count; i++) s.layers.Add(layers[i].Clone());
            return s;
        }

        public void CopyFrom(MaskLayerStack other)
        {
            layers = new List<MaskLayer>(other.layers.Count);
            for (int i = 0; i < other.layers.Count; i++) layers.Add(other.layers[i].Clone());
            active = Mathf.Clamp(other.active, 0, Mathf.Max(0, layers.Count - 1));
            cacheDirty = true;
        }

        // ---- groom file (v2)

        public void Write(BinaryWriter w)
        {
            w.Write(layers.Count);
            w.Write(active);
            for (int li = 0; li < layers.Count; li++)
            {
                MaskLayer L = layers[li];
                w.Write(L.name ?? "");
                w.Write(L.visible);
                w.Write(L.opacity);
                w.Write((int)L.blend);
                w.Write(L.locked);
                w.Write(L.isResolver);
                w.Write(L.value.Length);
                for (int i = 0; i < L.value.Length; i++) w.Write(L.value[i]);
                w.Write(L.cover);
            }
        }

        public void Read(BinaryReader r, int size)
        {
            int count = r.ReadInt32();
            active = r.ReadInt32();
            layers = new List<MaskLayer>(Mathf.Max(1, count));
            for (int li = 0; li < count; li++)
            {
                var L = new MaskLayer();
                L.name = r.ReadString();
                L.visible = r.ReadBoolean();
                L.opacity = r.ReadSingle();
                L.blend = (MaskBlend)r.ReadInt32();
                L.locked = r.ReadBoolean();
                L.isResolver = r.ReadBoolean();
                int n = r.ReadInt32();
                L.value = new float[n];
                for (int i = 0; i < n; i++) L.value[i] = r.ReadSingle();
                L.cover = r.ReadBytes(n);
                layers.Add(L);
            }
            Ensure(size, "Base");
        }

        // A v1 groom file has one flat buffer per mask: load it as a solid base layer.
        public void SetSingle(string name, float[] flat)
        {
            var L = new MaskLayer(name, flat.Length);
            Array.Copy(flat, L.value, flat.Length);
            for (int i = 0; i < L.cover.Length; i++) L.cover[i] = 255;
            layers = new List<MaskLayer> { L };
            active = 0;
            cacheDirty = true;
        }
    }
}
